#!/usr/bin/env bash
# Fetch canonical UniProt sequences and Human Protein Atlas RNA consensus
# tissue expression for the proteins used in BioDemo, and rewrite
# src/main/resources/data/proteins.ttl. Idempotent: run whenever you want
# to refresh against upstream. The generated file is committed so a reader
# can `mvn exec:java` without depending on network access.
#
# Sources:
#   UniProt canonical FASTA — https://rest.uniprot.org (CC BY 4.0)
#   Human Protein Atlas RNA consensus tissue expression —
#       https://www.proteinatlas.org/about/download (CC BY-SA 3.0)
#
# Tissue expression is filtered to nTPM ≥ 100 (roughly the HPA "elevated"
# cutoff) so the coexpression counts in the demo query are meaningful
# rather than swamped by low-noise ubiquitous background.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT_DIR}/src/main/resources/data/proteins.ttl"

HPA_URL="https://www.proteinatlas.org/download/tsv/rna_tissue_consensus.tsv.zip"
HPA_ZIP="/tmp/scry-webfunctions-demo-hpa.zip"
HPA_TSV="/tmp/scry-webfunctions-demo-hpa.tsv"
NTPM_THRESHOLD=100

# UniProt accession : HPA gene symbol : human-readable label. Order is the
# order rows appear in the output TTL.
PROTEINS=(
    "P68871:HBB:Hemoglobin subunit beta"
    "P69905:HBA1:Hemoglobin subunit alpha"
    "P02042:HBD:Hemoglobin subunit delta"
    "P69891:HBG1:Hemoglobin subunit gamma-1"
    "P02144:MB:Myoglobin"
    "P01308:INS:Insulin (preproinsulin)"
)

# --- fetch HPA (once, cached) --------------------------------------------
if [[ ! -f "$HPA_TSV" ]]; then
    echo "fetching $HPA_URL" >&2
    curl -sSL -o "$HPA_ZIP" "$HPA_URL"
    unzip -p "$HPA_ZIP" > "$HPA_TSV"
fi

# --- helpers --------------------------------------------------------------
fetch_sequence() {
    # Strip the FASTA header line and any embedded whitespace/newlines.
    curl -sS "https://rest.uniprot.org/uniprotkb/$1.fasta" | tail -n +2 | tr -d '[:space:]'
}

# Normalize an HPA tissue name into a URI-safe slug.
tissue_slug() {
    printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr ' -' '__' | tr -d '(),.'
}

# Print the tissues where HPA nTPM ≥ threshold for a given gene symbol.
# One tissue per line, sorted, deduped.
expressed_tissues() {
    awk -F'\t' -v g="$1" -v t="$NTPM_THRESHOLD" '$2 == g && $4+0 >= t { print $3 }' "$HPA_TSV" | sort -u
}

# --- emit TTL -------------------------------------------------------------
tmp="$(mktemp)"
tissue_names="$(mktemp)"

{
    cat <<'HEADER'
@prefix bio:  <http://tegmentum.ai/ns/scry-demo/bio/> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix up:   <http://purl.uniprot.org/uniprot/> .

# AUTO-GENERATED by scripts/build-data.sh. Do not edit by hand.
#   Sequences: UniProt canonical FASTA (rest.uniprot.org, CC BY 4.0).
#   Tissue expression: Human Protein Atlas rna_tissue_consensus.tsv
#     (CC BY-SA 3.0), filtered to nTPM ≥ 100.

HEADER

    for entry in "${PROTEINS[@]}"; do
        IFS=':' read -r accession gene label <<< "$entry"
        echo "fetching $accession ($gene)" >&2
        seq="$(fetch_sequence "$accession")"

        printf 'up:%s a bio:Protein ;\n' "$accession"
        printf '    rdfs:label "%s" ;\n' "$label"
        printf '    bio:sequence "%s" ;\n' "$seq"

        first=1
        while IFS= read -r tissue; do
            [[ -z "$tissue" ]] && continue
            slug="$(tissue_slug "$tissue")"
            printf '%s\t%s\n' "$slug" "$tissue" >> "$tissue_names"
            if [[ $first -eq 1 ]]; then
                printf '    bio:expressedIn bio:tissue_%s' "$slug"
                first=0
            else
                printf ' ,\n                    bio:tissue_%s' "$slug"
            fi
        done < <(expressed_tissues "$gene")

        if [[ $first -eq 1 ]]; then
            # Protein has no tissue above threshold — drop the trailing ; and
            # close with . on the sequence.
            printf ' .\n\n'
        else
            printf ' .\n\n'
        fi
    done

    echo "# Tissue labels."
    sort -u "$tissue_names" | while IFS=$'\t' read -r slug name; do
        printf 'bio:tissue_%s rdfs:label "%s" .\n' "$slug" "$name"
    done
} > "$tmp"

rm -f "$tissue_names"
mv "$tmp" "$OUT"
echo "wrote $OUT" >&2
